print("\n.........................Operators.........................\n")

# usage arithmetic operators
from math import ceil
print("1. Arithmetic Operators")
print("Result of 1+2          :", 1+2)
print("Result of 1.1+         :", 1.1+2)
print("Result of 2-1          :", 2-1)
print("Result of 2.0-1        :", 2.0-1)
print("Result of 1*2          :", 1*2)
print("Result of 1.0*2        :", 1.0*2)
print("Result of 10/2         :", 10/2)
print("Result of 4.5/2        :", 4.5/2)
print("Result of 14%4         :", 14%4)
print("Result of 14.75%4      :", 14.75%4)
print("Result of 16%3.5       :", 16%3.5)
print("Result of 2**3         :", 2**3)
print("Result of 2.0**3       :", 2.0**3)
print("Result of 2**3.0       :", 2**3.1)
print("Result of 14//4        :", 14//4) # integer division will divide normal division and then apply floor to that result
print("Result of 14.0//4      :", 14.0//4)
print("Result of -5//2        :", -5//2)
print("Result of 5//-2        :", 5//-2)
print("Ceil operation of 10.25:", ceil(10.25)) # it gives the next integer
print()

# usage of relational opertors (it returns only boolean result)
print("2. Relational Operators")
print("Result of 5<3                           : ", 5<3)
print("Result of 5>3                           : ", 5>3)
print("Result of 5<=4                          : ", 5<=4)
print("Result of 5>=5                          : ", 5>=5)
print("Type of 5<3                             : ", type(5<3))
print("Result of 'Hello'>'Python'              : ", 'Hello'>'Python')
print("Unicode representation of character H is: ", ord('H')) # ord() function returns unicode representation of characters
print("Unicode representation of character P is: ", ord('P'))
print("Result of ord('H')<ord('P')             : ", ord('H')<ord('P'))
print()

# usage of equality operators (it returns only boolean result)
print("3. Equality Operators")
print("Result of 10==10           : ", 10==10)
print("Result of 10==10.0         : ", 10==10.0)
print("Result of 10==100          : ", 10==100)
print("Result of 10!=10           : ", 10!=10)
print("Result of 1==True          : ", 1==True)
print("Result of 'Hello'=='Python': ", 'Hello'=='Python')
print("Result of 'Hello'=='Hello' : ", 'Hello'=='Hello')
print("Result of 'Hello'=='hello  : ", 'Hello'=='hello')
print("Result of 'Hello'==10      : ", 'Hello'==10)
print("Result of 10==20==30==40   : ", 10==20==30==40) # chaining also possible using equality operators
print("Result of 10!=20!=30!=40   : ", 10!=20!=30!=40)
print("Result of 10<20 != 30<40   : ", 10<20 != 30<40)
print("Result of 10<20 != 50<40   : ", 10<20 != 50<40)
print()

# usage of Logical Operators
print("4. Logical Operators")
# logical operators with boolean operands always returns boolean value
print("Result of True and True  : ", True and True)
print("Result of True and False : ", True and False)
print("Result of False and True : ", False and True)
print("Result of False and False: ", False and False)
print("Result of True or True   : ", True or True)
print("Result of True or False  : ", True or False)
print("Result of False or True  : ", False or True)
print("Result of False or False : ", False or False)
print("Result of not True       : ", not True)
print("Result of not False      : ", not False)
# logical opearators with non boolean values
print("Result of not 10     : ", not 10)
print("Result of not -10    : ", not -10)
print("Result of not 0      : ", not 0)
print("Result of not 'Hello': ", not "Hello")
print("Result of not ''     : ", not '')
print("Result of not ' '    : ", not ' ')
print("Result of 10 and 20  : ", 10 and 20)  # returns the last element of evaluation
print("Result of 10 and 0   : ", 10 and 0)
print("Result of 0 and 20   : ", 0 and 20)
print("Result of 10 or 20   : ", 10 or 20)
print("Result of 0 or 20    : ", 0 or 20)
print()